version: "3"

services:
    app:
        container_name: s2quat
        restart: always
        image: 127.0.0.1:5000/s2quat
        build: .
        depends_on: 
            - db
        environment: 
            - "TOKEN_SECRET=${TOKEN_SECRET}"
            - "PROTOCOL_PREFIX=${PROTOCOL_PREFIX}"
            - "ROOT_DOMAIN=${ROOT_DOMAIN}"
            - "PORT=${PORT}"
            - "DATABASE_URL=${DATABASE_SERVER}://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}"
        ports: 
            - "${PORT}:${PORT}"
            - "5555:5555" # for prisma studio
        networks:
            - database
    db:
        container_name: s2quat-db
        restart: always
        image: postgres:latest
        volumes: 
            - ./db:/var/lib/postgresql/data
        networks:
            - database
        ports: 
            - "${DATABASE_PORT}:${DATABASE_PORT}"

networks: 
    database:
