name: Deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy using ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd services/S2QUAT
            git pull
            restart
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USER }}
          pass: ${{ secrets.PASSWORD}}
